Theatre2GoWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from Theatre2GoWeb import view

urlpatterns = [
    path('', view.home, name='index'),
    # path('', view.friend_req_count, name='base'),
    path('artists/', include('artists.urls')),
    path('plays/', include('plays.urls')),
    path('theatres/', include('theatres.urls')),
    path('users/', include('users.urls')),

    path('accounts/', include('allauth.urls')),

    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path('friendship/', include('friendship.urls')),

    path('follow/', view.follow, name='follow'),
    path('unfollow/', view.unfollow, name='unfollow'),

    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()

artists/urls.py
from django.urls import path
from artists.views import ArtistListView, ArtistDetailView

urlpatterns = [
    path('', ArtistListView.as_view(), name='artists_view'),
    path('<int:pk>/', ArtistDetailView.as_view(), name="artist_view")
]

plays/urls.py
from django.urls import path
from artists.views import ArtistListView, ArtistDetailView
from plays.views import PlayListView, PlayDetailView

urlpatterns = [
    path('', PlayListView.as_view(), name='plays_view'),
    path('<int:pk>/', PlayDetailView.as_view(), name="play_view")
]

artists/models.py
from cloudinary.models import CloudinaryField
from django.contrib.auth.models import User
from django.db import models

from theatres.models import Theatre


class Artist(models.Model):
    name = models.CharField(max_length=255, null=False)
    shortBio = models.TextField()
    image = CloudinaryField('artistImage')
    associatedTheatres = models.ManyToManyField(Theatre)

    def __str__(self):
        return self.name


class ActorRole(models.Model):
    from plays.models import VaultPlay
    vaultPlay = models.ForeignKey(VaultPlay, on_delete=models.CASCADE)
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    role = models.CharField(max_length=255, null=False)


class UserFollow(models.Model):
    from plays.models import VaultPlay
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    artists = models.ManyToManyField(Artist)
    plays = models.ManyToManyField(VaultPlay)
    theatres = models.ManyToManyField(Theatre)

artists/views.py
from django.contrib.postgres.aggregates import StringAgg
from django.contrib.postgres.search import SearchQuery, SearchVector, SearchRank
from django.views.generic import ListView, DetailView
from friendship.models import Friend

from artists.models import Artist, UserFollow
from plays.models import VaultPlay


class ArtistListView(ListView):
    model = Artist
    context_object_name = 'artists'

    def get_queryset(self):
        if self.request.method == 'GET':
            queryset = Artist.objects.all()
            artist_type = self.request.GET.get('type', None)
            if artist_type is not None:
                if artist_type == "actor":
                    queryset = queryset.filter(actorrole__isnull=False).distinct()
                elif artist_type == "director":
                    queryset = queryset.filter(director__isnull=False).distinct()

            keywords = self.request.GET.get('q')
            if keywords:
                query = SearchQuery(keywords)
                name_vector = SearchVector('name', weight='A')
                theatre_vector = SearchVector(StringAgg('associatedTheatres__name', delimiter=' '), weight='B')
                play_vector = SearchVector(StringAgg('actorrole__vaultPlay__title', delimiter=' '), weight='B')
                vectors = name_vector + theatre_vector + play_vector
                queryset = queryset.annotate(rank=SearchRank(vectors, query)) \
                    .filter(rank__gte=0.2).order_by('-rank').distinct()

            return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        artist_type = self.request.GET.get('type', None)
        if artist_type is not None:
            context['type'] = artist_type

        if self.request.user.is_authenticated:
            count = Friend.objects.unrejected_request_count(user=self.request.user)
            context["f_count"] = count

        keywords = self.request.GET.get('q')
        if keywords:
            context['query'] = keywords

        return context


class ArtistDetailView(DetailView):
    model = Artist
    context_object_name = 'artist'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['vaultPlays'] = VaultPlay.objects.all()

        if self.request.user.is_authenticated:
            count = Friend.objects.unrejected_request_count(user=self.request.user)
            context["f_count"] = count

        if self.request.user.is_authenticated:
            try:
                context['follows'] = UserFollow.objects.get(user=self.request.user).artists.filter(pk=self.get_object().id).exists()
            except UserFollow.DoesNotExist:
                context['follows'] = False

        return context

templates/artists/artist_detail.html
{% extends "base.html" %}
{% load cloudinary %}
{% block title %}{{ artist.name }}{% endblock %}
{% block content %}
    <div>
        <!-- Header with theatre name and follow button -->
        <div>
            <div class="container" style="background-color: rgba(0, 0, 0, 0.2)">
                <div class="row pt-2">
                    <div class="col-auto">
                        <p class="h1">{{ artist.name }}</p>
                    </div>
                    <div class="col-auto pt-2">
                        {% include 'follow.html' with name="artist" id=artist.id %}
                    </div>
                </div>
            </div>
        </div>

        <!-- Artist info -->
        <div class="mx-5 mt-3">
            <div class="row justify-content-between align-items-center">
                <div class="col-md-8">
                    <p class="lead">{{ artist.shortBio }}</p>
                </div>
                <div class="col-auto">
                    {% cloudinary artist.image format="jpg" width=240 height=160 crop="fill" %}
                </div>
            </div>
            <hr>
            <div>
                <h4>Appeared in:</h4>
                <div class="row">
                    {% for assocTheatre in artist.associatedTheatres.all %}
                        <div class="col-auto">
                            <ul class="list-group list-group-flush">
                                <a href="{% url 'theatre_view' assocTheatre.id %}"
                                   class="list-group-item list-group-item-action list-group-item-dark"
                                ><b>{{ assocTheatre.name }}</b></a>
                            </ul>
                            <br>
                            {% for actor_role in artist.actorrole_set.all %}
                                {% if actor_role.vaultPlay.theatre.name == assocTheatre.name %}
                                    <li class="list-group-item list-group-item-dark">
                                        {{ actor_role.vaultPlay.title }}
                                    </li>
                                    <li class="list-group-item list-group-item-light">
                                        {{ actor_role.role }}
                                    </li>
                                    <br>
                                {% endif %}
                            {% endfor %}

                            {% for vaultPlay in vaultPlays %}
                                {% if vaultPlay.theatre.id == assocTheatre.id %}
                                    {% if vaultPlay.director.name == artist.name %}
                                        <li class="list-group-item list-group-item-dark">
                                            {{ vaultPlay.title }}
                                        </li>
                                        <li class="list-group-item list-group-item-light">
                                            Director
                                        </li>
                                        <br>
                                    {% endif %}
                                {% endif %}
                            {% endfor %}
                        </div>
                        <br>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/artists/artist_list.html
{% extends "base.html" %}
{% block title %}
    {% if type == "director" %}
        Directors
    {% elif type == "actor" %}
        Actors
    {% else %}
        Artists
    {% endif %}
{% endblock %}
{% block content %}
    <div class="container">
        <form class="input-group rounded mb-3" action="{% url 'artists_view' %}" method="get">
            <input name="type" type="hidden" value="{{ type }}">
            <input name="q" type="search" class="form-control rounded" placeholder="Search" aria-label="Search"
                   aria-describedby="search-addon"/>
            <span class="input-group-text border-0" id="search-addon">
                <i class="fas fa-search"></i>
             </span>
        </form>
        {% if query %} Search results for: {{ query }}
            <form action="{% url 'artists_view' %}" method="get">
                <input name="type" type="hidden" value="{{ type }}">
                <input type="hidden" name="q" value="">
                <input type="submit" value="Clear" class="btn btn-outline-dark">
            </form>
        {% endif %}
        <div class="row row-cols-1 row-cols-md-4 g-4">
            {% for artist in artists %}
                <div class="col">
                    <div class="card shadow-lg h-100">
                        <div class="bg-image hover-overlay ripple text-center" data-mdb-ripple-color="light">
                            <img
                                    src="{{ artist.image.url }}"
                                    class="img-fluid"
                            />
                            <a href="{% url 'artist_view' artist.id %}">
                                <div class="mask" style="background-color: rgba(251, 251, 251, 0.15)"></div>
                            </a>
                        </div>
                        <div class="card-body">
                            <h5 class="card-title">{{ artist.name }}</h5>
                            {% for assocTheatre in artist.associatedTheatres.all %}
                                <p class="h6 card-subtitle mb-2 text-muted">{{ assocTheatre.name }}</p>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}