Theatre2GoWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from Theatre2GoWeb import view

urlpatterns = [
    path('', view.home, name='index'),
    # path('', view.friend_req_count, name='base'),
    path('artists/', include('artists.urls')),
    path('plays/', include('plays.urls')),
    path('theatres/', include('theatres.urls')),
    path('users/', include('users.urls')),

    path('accounts/', include('allauth.urls')),

    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path('friendship/', include('friendship.urls')),

    path('follow/', view.follow, name='follow'),
    path('unfollow/', view.unfollow, name='unfollow'),

    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()

plays/urls.py
from django.urls import path
from artists.views import ArtistListView, ArtistDetailView
from plays.views import PlayListView, PlayDetailView

urlpatterns = [
    path('', PlayListView.as_view(), name='plays_view'),
    path('<int:pk>/', PlayDetailView.as_view(), name="play_view")
]

theatres/urls.py
from django.urls import path
from .views import TheatreListView, TheatreDetailView

urlpatterns = [
    path('', TheatreListView.as_view(), name='theatres_view'),
    path('<int:pk>/', TheatreDetailView.as_view(), name="theatre_view")
]

plays/models.py
from cloudinary.models import CloudinaryField
from django.db import models
from django.db.models.signals import post_save
from star_ratings.models import UserRating

from artists.models import Artist
from theatres.models import Theatre


def on_rating_save(sender, instance, **kwargs):
    print("AAAAAAAAAAAAAAAAAA")


post_save.connect(on_rating_save, sender=UserRating)


class VaultPlay(models.Model):
    title = models.CharField(max_length=255, null=False)
    shortBio = models.TextField()
    theatre = models.ForeignKey(Theatre, on_delete=models.CASCADE)
    director = models.ForeignKey(Artist, on_delete=models.SET_NULL, related_name="director", null=True)
    writer = models.CharField(max_length=255, null=False)
    image = CloudinaryField('playImage')
    carouselImage1 = CloudinaryField('carouselImage1', blank=True, null=True)
    carouselImage2 = CloudinaryField('carouselImage2', blank=True, null=True)
    carouselImage3 = CloudinaryField('carouselImage3', blank=True, null=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.title


class Play(models.Model):
    startTime = models.DateTimeField()
    endTime = models.DateTimeField()
    vaultPlay = models.ForeignKey(VaultPlay, on_delete=models.CASCADE)

    def __str__(self):
        return self.vaultPlay.title

theatres/models.py
from django.db import models
from cloudinary.models import CloudinaryField
from phonenumber_field.modelfields import PhoneNumberField
from location_field.models.plain import PlainLocationField


class TheatreType(models.Model):
    type = models.CharField(max_length=255, null=False)

    def __str__(self):
        return self.type


class Theatre(models.Model):
    name = models.CharField(max_length=255, null=False)
    description = models.TextField()
    phone = PhoneNumberField(null=False, blank=False)
    mail = models.EmailField()
    website = models.CharField(max_length=255, null=True)
    location = PlainLocationField(based_fields=['city'], zoom=7)
    address = models.CharField(max_length=255, null=False, default='Timisoara, Romania')
    image = CloudinaryField('theatreImage')
    theatreType = models.ForeignKey(TheatreType, on_delete=models.CASCADE)  # DELETE ALL THEATRES OF THE DELETED TYPE

    def __str__(self):
        return self.name


class WorkProgram(models.Model):
    theatre = models.OneToOneField(Theatre, on_delete=models.CASCADE)
    description = models.CharField(max_length=255, null=False)
    Monday = models.CharField(max_length=255, null=False)
    Tuesday = models.CharField(max_length=255, null=False)
    Wednesday = models.CharField(max_length=255, null=False)
    Thursday = models.CharField(max_length=255, null=False)
    Friday = models.CharField(max_length=255, null=False)
    Saturday = models.CharField(max_length=255, null=False)
    Sunday = models.CharField(max_length=255, null=False)

    def __str__(self):
        return self.description

theatres/views.py
from django.contrib.postgres.search import SearchQuery, SearchVector, SearchRank
from django.db.models import Avg
from django.views.generic import ListView, DetailView
from friendship.models import Friend
from star_ratings.models import Rating

from artists.models import UserFollow
from theatres.models import Theatre


class TheatreListView(ListView):
    model = Theatre
    context_object_name = 'theatres'

    def get_queryset(self):
        if self.request.method == 'GET':
            queryset = Theatre.objects.all()
            theatre_type = self.request.GET.get('type')
            if theatre_type:
                queryset = queryset.filter(theatreType__type__exact=theatre_type).distinct()

            keywords = self.request.GET.get('q')
            if keywords:
                query = SearchQuery(keywords)
                name_vector = SearchVector('name', weight='A')
                artist_vector = SearchVector('artist__name', weight='B')
                vectors = name_vector + artist_vector
                queryset = queryset.annotate(rank=SearchRank(vectors, query)) \
                    .filter(rank__gte=0.3).order_by('-rank').distinct()

            return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if self.request.user.is_authenticated:
            count = Friend.objects.unrejected_request_count(user=self.request.user)
            context["f_count"] = count

        theatre_type = self.request.GET.get('type', None)
        if theatre_type is not None:
            context['type'] = theatre_type

        keywords = self.request.GET.get('q')
        if keywords:
            context['query'] = keywords

        return context


class TheatreDetailView(DetailView):
    model = Theatre
    context_object_name = 'theatre'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if self.request.user.is_authenticated:
            count = Friend.objects.unrejected_request_count(user=self.request.user)
            context["f_count"] = count

        theatre = self.get_object()
        if self.request.user.is_authenticated:
            try:
                context['follows'] = UserFollow.objects.get(user=self.request.user).theatres.filter(
                    pk=theatre.id).exists()
            except UserFollow.DoesNotExist:
                context['follows'] = False

        vault_play_ids = []

        for vault_play in theatre.vaultplay_set.all():
            vault_play_ids.append(vault_play.id)

        print(vault_play_ids)
        try:
            context['general_rating'] = round(Rating.objects
                                            .filter(object_id__in=vault_play_ids)
                                            .aggregate(Avg('average'))['average__avg'], 1)
        except:
            context['general_rating'] = "No play added yet"

        return context

templates/theatres/theatre_detail.html
{% extends "base.html" %}
{% load cloudinary %}
{% block title %}{{ theatre.name }}{% endblock %}
{% block content %}
    <div>
        <!-- Header with theatre name and follow button -->
        <div class="container" style="background-color: rgba(0, 0, 0, 0.2)">
            <div class="row justify-content-between pt-2 align-items-center">
                <div class="col-auto">
                    <div class="row">
                        <div class="col-auto">
                            <p class="h1">{{ theatre.name }}</p>
                        </div>
                        <div class="col-auto pt-2">
                            {% include 'follow.html' with name="theatre" id=theatre.id %}
                        </div>
                    </div>
                </div>
                <div class="col-auto">
                    <p class="h5">{{ theatre.workprogram.description }}</p>
                </div>
            </div>
        </div>

        <!-- Theatre information -->
        <div class="mx-5 mt-3">

            <!-- Description and photo -->
            <div class="row justify-content-between">
                <div class="col-md-8">
                    <p class="h4">General rating: {{ general_rating }}</p>
                    <p class="lead">{{ theatre.description }}</p>
                </div>
                <div class="col-auto">
                    {% cloudinary theatre.image format="jpg" width=240 height=160 crop="fill" %}
                </div>
            </div>

            <hr>

            <!-- Contact and location -->
            <div class="row justify-content-between">
                <div class="col-auto">
                    <div class="row">
                        <p class="h2">
                            Contact:
                        </p>
                    </div>

                    <div class="row">
                        <div class="col">
                            <p><b>Phone number: </b>{{ theatre.phone }}</p>
                            <p><b>E-Mail: </b>
                                <a class="link-dark" href="mailto:{{ theatre.mail }}">
                                    <u>{{ theatre.mail }}</u>
                                </a></p>
                            <p><b>Website: </b>
                                <a class="link-dark"
                                   href="{{ theatre.website }}">
                                    <u>{{ theatre.website }}</u>
                                </a>
                            </p>

                            <p><b>Address: </b>{{ theatre.address }}</p>
                        </div>
                    </div>
                </div>

                <div class="col-4">
                    <h4>Google Maps</h4>
                    <div id="map" style="height: 80%"></div>
                </div>
            </div>

            <hr>

            <!-- Plays schedule -->
            <div>
                <div class="row">
                    <p class="h2">Plays schedule:</p>
                </div>

                <div class="accordion" id="accordionExample">
                    {% for vault_play in theatre.vaultplay_set.all %}
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="heading{{ vault_play.id }}">
                                <button
                                        class="accordion-button"
                                        type="button"
                                        data-mdb-toggle="collapse"
                                        data-mdb-target="#collapse{{ vault_play.id }}"
                                        aria-expanded="true"
                                        aria-controls="collapse{{ vault_play.id }}"
                                >
                                    {{ vault_play.title }}
                                </button>
                            </h2>
                            <div
                                    id="collapse{{ vault_play.id }}"
                                    class="accordion-collapse collapse show"
                                    aria-labelledby="heading{{ vault_play.id }}"
                                    data-mdb-parent="#accordionExample"
                            >
                                <div class="accordion-body">
                                    {% for play in vault_play.play_set.all %}
                                        <a href="{% url 'play_view' play.id %}" class="link-dark">
                                            <p class="note note-light">
                                                <i class="far fa-calendar-alt"></i> {{ play.startTime.date }}, {{ play.startTime|date:"l" }}
                                                <br>
                                                <i class="far fa-clock"></i> {{ play.startTime.time }}-{{ play.endTime.time }}
                                            </p>
                                        </a>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

    <!-- Google Maps Scripts -->
    <script defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBHfHQEXiF-tgiuRc5NIH_hybFrvfOhrbM&callback=initMap&libraries=&v=weekly"
    ></script>

    <script>
        // Initialize and add the map
        function initMap() {

            const location = "{{theatre.location}}";
            const [lat, lng] = location.split(",").map(Number)

            const theatreLocation = {lat: lat, lng: lng};

            // The map, centered at theatre location
            const map = new google.maps.Map(document.getElementById("map"), {
                zoom: 13,
                center: theatreLocation,
            });

            // The marker
            const marker = new google.maps.Marker({
                position: theatreLocation,
                map: map,
            });
        }

        google.maps.event.addDomListener(window, 'load', initialize);
    </script>
{% endblock content %}

templates/theatres/theatre_list.html
{% extends "base.html" %}
{% block title %}
    {% if type == "state" %}
        State Theatres
    {% elif type == "independent" %}
        Independent Theatres
    {% else %}
        Theatres
    {% endif %}
{% endblock %}
{% block content %}
    <div class="container-fluid">
        <form class="input-group rounded mb-3" action="{% url 'theatres_view' %}" method="get">
             <input name="type" type="hidden" value="{{ type }}">
             <input name="q" type="search" class="form-control rounded" placeholder="Search" aria-label="Search" aria-describedby="search-addon" />
             <span class="input-group-text border-0" id="search-addon">
                <i class="fas fa-search"></i>
             </span>
        </form>
        {% if query %} Search results for: {{ query }}
            <form action="{% url 'theatres_view' %}" method="get">
                <input name="type" type="hidden" value="{{ type }}">
                <input type="hidden" name="q" value="">
                <input type="submit" value="Clear" class="btn btn-outline-dark">
            </form>
        {% endif %}
        {% for theatre in theatres %}
            <div class="card mb-3 shadow-lg">
                <div class="row g-0">
                    <div class="col-md-4">
                        <div class="bg-image hover-overlay ripple" data-mdb-ripple-color="light">
                            <img
                                    src="{{ theatre.image.url }}"
                                    class="img-fluid"
                            />
                            <a href="{% url 'theatre_view' theatre.id %}">
                                <div class="mask" style="background-color: rgba(251, 251, 251, 0.15)"></div>
                            </a>
                        </div>
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">{{ theatre.name }}</h5>
                            <p class="card-text">
                                {{ theatre.description }}
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock content %}